// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // `prisma db push`/`migrate` always run against the local SQLite file.
  // The remote Turso database's schema is synced separately via the Turso
  // CLI, since the schema engine doesn't speak Turso's libsql wire protocol.
  datasource: {
    url: "file:./dev.db",
  },
});
